module.exports = {
    onlyOwner: "Ownable: caller is not the owner",
    nftIdsLength: "NineWorldsMinigame. NftIds length missmatch",
    powersLength: "NineWorldsMinigame. Powers length missmatch",
    matchNftExceedMax: "NineWorldsMinigame: Match nft amount exceed max",
    matchNftAmountExceedUser: "NineWorldsMinigame: Match nft amount exceed user nft amount",
    matchNftAmountExceedUserValid: "NineWorldsMinigame: Match nft amount exceed user valid nfts to play",
    randomNumber: "NineWorldsMinigame: RandomNumber not available yet",
    rerroll: "Rerroll not available",
    linkFounds: "NineWorldsMinigame: Not enough LINK, fill contract with LINK",
    notInitializedMatch: "NineWorldsMinigame: Match is not created or initialized",
    initializedMatch: "NineWorldsMinigame: Match is already initialized",
    matchFinished: "NineWorldsMinigame: Match is finished",
    reorder: "NineWorldsMinigame: Reorder not available: player power is less than computer power",
    pendingMatch: "NineWorldsMinigame: Pending match",
    noPendingMatch: "NineWorldsMinigame: No pending match to initialize",
    plaeyerPowerLessThanComputer: "NineWorldsMinigame: Reorder not available: player power is less than computer power",
    nftIdsLentghMissmastch: "NineWorldsMinigame. NftIds length missmatch",
    porwerLengthMissmatch: "NineWorldsMinigame. Powers length missmatch",
    wrongIndexes: "NineWorldsMinigame: Invalid indexes, either both equal or gte matchCount"
};